version: "3"

services:
  movieweb:
    container_name: movieweb
    image: "mysql:8.0.34-oracle"
    ports:
      - "3306:3306"
    networks:
      - movieWeb-network
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mysql"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - movieWeb-volume:/var/lib/mysql
      - "./scripts:/docker-entrypoint-initdb.d"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - movieweb
    restart: always
    networks:
      - movieWeb-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://movieweb:3306/mysql

volumes:
  movieWeb-volume:

networks:
  movieWeb-network: