version: "3"

services:
  mysql:
    container_name: movieWeb-db
    image: "mysql:8.0.34-oracle"
    ports:
      - "3307:3306"
    networks:
      - movieWeb-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    restart: always
    volumes:
      - movieWeb-volume:/var/lib/mysql

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - movieWeb-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    volumes:
      - movieWeb-volume:/var/lib/mysql

volumes:
  movieWeb-volume:

networks:
  movieWeb-network: